# Generated by Django 5.0.1 on 2026-02-01 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_bookinterest_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=200)),
                ('is_fiction', models.BooleanField(default=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('want_to_read', 'Want to Read'), ('currently_reading', 'Currently Reading'), ('finished', 'Finished')], default='want_to_read', max_length=20)),
                ('rating', models.IntegerField(blank=True, help_text='Rating from 1 to 5', null=True)),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_book_lists',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='user_book_l_user_id_bb86af_idx'), models.Index(fields=['title'], name='user_book_l_title_25d149_idx')],
            },
        ),
    ]
