# Generated by Django 5.0.1 on 2026-02-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userbooklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooklist',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
