# Generated by Django 5.0.1 on 2026-02-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userbooklist_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooklist',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('did_not_like', 'Did Not Like'), ('neutral', 'Neutral'), ('liked_it', 'Liked It'), ('great_book', 'Great Book')], max_length=20, null=True),
        ),
    ]
