# Generated by Django 5.0.1 on 2026-02-01 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userbooklist_sentiment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbooklist',
            unique_together={('user', 'title')},
        ),
    ]
