# Generated by Django 5.0.1 on 2026-02-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='auto_approve_club_memberships',
            field=models.BooleanField(default=False, help_text='Automatically approve club membership requests (set status to active instead of pending)'),
        ),
    ]
